<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>IMYSHook-melon</AssemblyName>
    <Description>melonloader implementation of IMYSHook</Description>
    <Version>1.0.6</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>IMYSHook</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <PropertyGroup>
    <GamePath>C:\Users\husky\imys_r_exe</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <GameDlls Include="
          $(GamePath)\MelonLoader\net6\*.dll;
		      $(GamePath)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll;
		      $(GamePath)\MelonLoader\Il2CppAssemblies\Il2Cpp*.dll;
		      $(GamePath)\MelonLoader\Il2CppAssemblies\spine-*.dll;
		      $(GamePath)\MelonLoader\Il2CppAssemblies\Unity*.dll">
    </GameDlls>
    <Reference Include="@(GameDlls)">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy config.json $(OutDir)&#xD;&#xA;copy SS_Notification.ps1 $(OutDir)" />
  </Target>
</Project>